### PR TITLE
Add resources for Node and React to README

### PR DESCRIPTION
**Pull request by mindy-m**

### CODE REVIEW

**Review by diffalot — CHANGES_REQUESTED** [review]
These are great resources and I’m glad you put them in the readme and started up a pull request 🖖

To merge this request I’d like to separate it into two PRs so that we don’t have changes to the readme mixed in with changes to the `package.json` and `yarn.lock`.  And it will make discussion easier if there’s just one topic to talk about in the pull request discussion thread.

I’d be happy to share a quick `git` recipe for preserving the optimization commit on a new branch and then using interactive rebase on this branch to make that chore of making two PRs out of this one easier, so don’t hesitate to ask here or in Slack.

**Comment by mindy-m** [comment]
Sure, if you could share that with me that'd be great.

**Comment by diffalot** [comment]
# using `git rebase main` and `git rebase -i main`  

https://youtu.be/mBKqXduT1Dg

In that video I run through a branch of mine that needed to be broken apart in a similar way, and then I ran through it with yours as well.

The gist of it is that you can detach the individual commits of your pull request from each other and place them into their own branches.  (Git makes branching really cheap so I often have emojis scattered around my git tree like pushpins with `git checkout 📱` if I might want to go back to that location soon, and for a more permanent marker I use `git tag ⚡️`) Sometimes it gets a little messy but each branch is a a save point I can go back to if I get lost, so I tend to keep them around util I've submitted the PR.

## Creating a `readme` branch with just the readme commit

* first I'd checkout your `maybe-origin/main` branch as `readme-and-optimize` since that's where those commits live in your fork; to me it looks like they are at `mindy-m/main` so checking the logs will be important when we get there, and I'm just going to refer to it as the `readme-and-optimize` branch from here on out.

```
git checkout `main`
git checkout -b `readme-and-optimize`
```

* then I'd take a look at the log between `main` (and this time I mean the main branch on the upstream at `code-circles/main-app/main`) and `readme-and-optimize` to make sure I'm dealing the correct branches you can reset your main branch to make sure it's tracking the upstream central repository with:

```
git remote add code-circles-upstream git@github.com:code-circles/main-app.git
git fetch --all
git checkout main
git checkout -b main-backup     # we're about to overwrite our previous local main branch....
git checkout main
git reset --hard code-circles-upstream/main
```
* now we can look at the log and I'm going to be referring to the the copy of upstream/main that you have locally as main as main from here on out 

```
git log --oneline main...readme-and-optimize
e7389a4 (HEAD -> readme-and-optimize, mindy-m/main) Optimize build
22aa707 Add resources for Node and React to README
```

* the `--oneline` option makes it a little less noisy.  And now we have the commits we want to separate
* to create a `readme` branch with just `22aa707 Add resources for Node and React to README` in it you can do

```
git checkout -b readme 22aa707 
```

* and git log will show just the one commit 

```
git log --oneline main...readme
22aa707 (HEAD -> readme) Add resources for Node and React to README
```

* so that one is ready to start a PR for, and I think starting a new pr is usually the easiest, but I often feel very attached to a PR and can't bring myself to close the old one.  At any rate, that's up to you.

## On to the optimize branch: it's a little different

* first: 

```
git checkout -b optimize e7389a4 
```

* we still have the readme in there because `e7389a4` was built on top of the readme commit even though they are discrete patches that don't touch any of the same lines of code or even files.
 
```
git log --oneline main...optimize
e7389a4 (HEAD -> optimize, mindy-m/main, readme-and-optimize) Optimize build
22aa707 (readme) Add resources for Node and React to README
```

### option one: `git cherry-pick`

* so we have two direct options `git cherry pic` to add on just the optimize commit to a new branch off of main:

```
git checkout main
git checkout -b optimize-cherry-pick
```

* now that we're on a branch that is identical to main we can

```
git cherry-pick e7389a4
[optimize-cherry-pick 3541b1e] Optimize build
 Author: Mindy Medeiros <mmedei6@wgu.edu>
 Date: Tue May 25 07:30:38 2021 -0400
 3 files changed, 2125 insertions(+), 55 deletions(-)
 create mode 100644 package-lock.json
```

* and git log will show just the commit we want

```
git log --oneline main...optimize-cherry-pick
3541b1e (HEAD -> optimize-cherry-pick) Optimize build
```

### Option 2 Interactive rebase with `git rebase -i`

* And the other method is rebase which is more powerful, dangerous, and error prone because it gives you unlimited options for rewriting the commit history of your branch.
* So we'll go back to the branch `readme-and-optimize` where we began our cherry pick and do it all over again with rebase

```
git checkout readme-and-optimize
git log --oneline main...readme-and-optimize
e7389a4 (HEAD -> readme-and-optimize, mindy-m/main, optimize) Optimize build
22aa707 (readme) Add resources for Node and React to README
```

from there we rebase with `-i` (I think that's the short version of `--interactive` but you'll have to check `man git-rebase` to be sure) and that will give us the text file we can use to reorder commits, join them together, pull in commits that weren't even on the branch, and all kinds of dangerous things that happen when you rewrite history, and since it's just a text area, it will let you put things in there that will just never work.  It's better to rebase sooner than later because then there's less history to rewrite and less chance of having to manually resolve conflicting edits.

(`git rebase -i main` will use your system's default editor, probably `vim`, which has a steep learning cliff and requires you to hit the following keys in sequence to exit: `esc`, `:`, `q`, `!`, `enter`, and nowhere on the screen will it tell you that. But `nano` works more like a normal text editor and you can ask the computer to open a specific one with an environment variable inserted before your git command, for VSCode, if you have the command `code` installed, it's `EDITOR=code git rebase -i main`, or to stay in the terminal, use  `EDITOR=vim git rebase -i main` or `EDITOR=nano git rebase -i main`  )

and finally, our text file will have the following two lines that you can interact with and some brief instructions.  Notice that optimize is on the bottom of the list because it came after the readme commit.  What the screen shows right now is the current state of this branch which has these two commits selected, "picked", to be in it. In the video I deleted the line with the readme commit, but changing the word `pick` to `drop` or just the letter `d` and that's helpfully revealed in the instructions as `d, drop <commit> = remove commit`

```
  pick 22aa707 Add resources for Node and React to README
  pick e7389a4 Optimize build

  # Rebase c6a6513..e7389a4 onto c6a6513 (2 commands)
  #
  # Commands:
  # p, pick <commit> = use commit
  # r, reword <commit> = use commit, but edit the commit message
  # e, edit <commit> = use commit, but stop for amending
  # s, squash <commit> = use commit, but meld into previous commit
  # f, fixup <commit> = like "squash", but discard this commit's log message
  # x, exec <command> = run command (the rest of the line) using shell
  # b, break = stop here (continue rebase later with 'git rebase --continue')
  # d, drop <commit> = remove commit
  # l, label <label> = label current HEAD with a name
  # t, reset <label> = reset HEAD to a label
  # m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
  # .       create a merge commit using the original merge commit's
  # .       message (or the oneline, if no original merge commit was
  # .       specified). Use -c <commit> to reword the commit message.
  #
  # These lines can be re-ordered; they are executed from top to bottom.
  #
  # If you remove a line here THAT COMMIT WILL BE LOST.
  #
  # However, if you remove everything, the rebase will be aborted.
  #
```

* so once you've edited the lines to drop the readme commit  or remove it entirely it will look a little like this:

```
  drop 22aa707 Add resources for Node and React to README
  pick e7389a4 Optimize build
```

* and when you save and exit the editor (`esc`, `:`, `w`, `q`, `enter` in vim and `Ctrl+o`, `Ctrl+x` in nano), git will apply your changes and if you look at the log you'll see

```
 git log --oneline main...readme-and-optimize
d3b0e1e (HEAD -> readme-and-optimize) Optimize build
```

* and one last thing before pushing and opening a pull request:

```
git checkout -b optimize-rebased
```

> lol, that was way longer than I thought it would be...... I'll try to clean up the formatting, and please let me know if I can help out.

**Comment by mindy-m** [comment]
Thanks Alice!   That's super helpful.  Give me a little bit and I'll make the requested changes.

**Comment by mindy-m** [comment]
I've created a new pull request in place of this one.

**Pull request closed without merging**
